[config]
reload_apps = false

[templates.quickshell]
input_path = "~/.config/matugen/templates/qs_colors.json.template"
output_path = "/tmp/qs_colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf.template"
output_path = "/tmp/kitty-matugen-colors.conf"

[templates.cava]
input_path = "~/.config/matugen/templates/cava-colors.ini.template"
output_path = "~/.config/cava/colors"

[templates.swayosd]
input_path = "~/.config/matugen/templates/swayosd.css.template"
output_path = "~/.config/swayosd/style.css"

[templates.gtk]
input_path = "~/.config/matugen/templates/gtk.css.template"
output_path = "~/.cache/matugen/colors-gtk.css"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.lua.template"
output_path = "~/.config/hypr/colors.lua"
